# Fetching from the official upstream chart repos.
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
  - name: cloudposse
    url: https://charts.cloudposse.com/incubator/
  - name: datawire
    url: https://www.getambassador.io
