#!/bin/bash

PROFILE=jimconn

maas_machine_id ()
{
    local id;
    id=$1;
    [[ -z "$id" ]] && {
        echo "Please provide a machine name to seek." 1>&2;
        return 1
    };
    echo "$all_nodes" | jq -Mr --arg name "$id" '
      .[] |
        select(.hostname == $name) |
          .boot_interface.system_id'
}

maas_nodes()
{
  maas "$PROFILE" nodes read
}

#IP_MODE="static"
IP_MODE="dhcp"

echo "Reading all nodes..."
all_nodes=$(maas_nodes)

for nuc in nuc-{01..18}; do
  IFS='-' read -r _ static_octet <<< "$nuc"
  static_octet=${static_octet/^0/}

  static_octet=$((${static_octet#0} + 50))
  sys_id="$(maas_machine_id $nuc)"
  iface_id=$(echo "$all_nodes" | \
    jq --arg node_id "$sys_id" -Mr '.[] | select(.system_id == $node_id and .status_name == "Ready") | .interface_set[0].id')
  subnet_id=$(echo "$all_nodes" | \
    jq --arg node_id "$sys_id" -Mr '.[] | select(.system_id == $node_id and .status_name == "Ready") | .interface_set[0].links[0].id')


  if [[ -n "$iface_id" ]]; then
    echo "Updating $nuc..."

    maas "$PROFILE" interface unlink-subnet "$sys_id" "$iface_id" id="$subnet_id"
    #maas "$PROFILE" interface link-subnet "$sys_id" "$iface_id" mode="$IP_MODE" subnet=192.168.2.0/24 ip_address="192.168.2.$static_octet"
    maas "$PROFILE" interface link-subnet "$sys_id" "$iface_id" mode="$IP_MODE" subnet=192.168.2.0/24
  fi
done
