
%{ if arm64_support }
image:
  registry: gcr.io
  repository: k8s-staging-external-dns/external-dns
  tag: v20210203-v0.7.6-28-g44288212-arm64v8

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "utility"
  effect: "NoSchedule"

nodeSelector:
  beta.kubernetes.io/arch: arm64
%{ else }
%{ endif }

rbac:
  create: true

serviceAccount:
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: "arn:${aws_partition}:iam::${aws_account_id}:role/${cluster_id}-external-dns"

txtOwnerId: ${cluster_id}
policy: sync

aws:
  zoneType: public
  region: ""

provider: aws

sources:
  - service
  - ingress

domainFilters:
  - ${domain_name}

triggerLoopOnEvent: true

logLevel: debug

replicas: 1

crd:
  ## Install and use the integrated DNSEndpoint CRD
  create: true