# define defaults for values in values.yaml
---
pollingTime: 60

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi

autoscaling:
  enabled: false

livenessProbe:
  timeoutSeconds: 1

readinessProbe:
  timeoutSeconds: 1

agent:
  enabled: false
  image:
    repository: docker.io/datawire/aes
    tag: 1.12.0
