# a11y-profile-manager
# Autogenerated from man page /usr/share/man/man1/a11y-profile-manager.1.gz
complete -c a11y-profile-manager -s h --description 'Show summary of options.'
complete -c a11y-profile-manager -s v -l version --description 'Displays the release version and exits.'
complete -c a11y-profile-manager -s l -l list --description 'List available accessibility profiles.'
complete -c a11y-profile-manager -s L -l list-detailed --description 'List accessibility profiles with more details.'
complete -c a11y-profile-manager -s g -l get --description 'Get the currently active profile.'
complete -c a11y-profile-manager -s s -l set --description 'Set the active profile, using its directory name, as shown with the -l or -L …'
complete -c a11y-profile-manager -s d -l deactivate --description 'Deactivate the currently active profile AUTHOR A11y-profile-manager was devel…'

