# applycal
# Autogenerated from man page /usr/share/man/man1/applycal.1.gz
complete -c applycal -s v --description 'Verbose mode.'
complete -c applycal -s a --description 'Apply or re-apply calibration (default).'
complete -c applycal -s u --description 'Remove calibration.'
complete -c applycal -s c --description 'Check calibration.'

