# argdist-bpfcc
# Autogenerated from man page /usr/share/man/man8/argdist-bpfcc.8.gz
complete -c argdist-bpfcc -s h --description 'Print usage message.'
complete -c argdist-bpfcc -s p --description 'Trace only functions in the process PID.'
complete -c argdist-bpfcc -s z --description 'When collecting string arguments (of type char*), collect up to STRING_SIZE  …'
complete -c argdist-bpfcc -s i --description 'Print the collected data every INTERVAL seconds.  The default is 1 second.'
complete -c argdist-bpfcc -s n --description 'Print the collected data COUNT times and then exit.'
complete -c argdist-bpfcc -s v --description 'Display the generated BPF program, for debugging purposes.'
complete -c argdist-bpfcc -s T --description 'When collecting frequency counts, display only the top TOP entries.'
complete -c argdist-bpfcc -s H -s C --description 'One or more probe specifications that instruct argdist which functions to pro…'
complete -c argdist-bpfcc -s I --description 'One or more header files that should be included in the BPF program.'

