# biolatency-bpfcc
# Autogenerated from man page /usr/share/man/man8/biolatency-bpfcc.8.gz
complete -c biolatency-bpfcc -s T --description 'Include timestamps on output.'
complete -c biolatency-bpfcc -s m --description 'Output histogram in milliseconds.'
complete -c biolatency-bpfcc -s D --description 'Print a histogram per disk device.'
complete -c biolatency-bpfcc -s h --description 'Print usage message.'

