# biotop-bpfcc
# Autogenerated from man page /usr/share/man/man8/biotop-bpfcc.8.gz
complete -c biotop-bpfcc -s C --description 'Don\'t clear the screen.'
complete -c biotop-bpfcc -s r --description 'Maximum number of rows to print.  Default is 20.'
complete -c biotop-bpfcc -s p --description 'Trace this PID only.'

