# bundle-update
# Autogenerated from man page /usr/share/man/man1/bundle-update.1.gz
complete -c bundle-update -l group --description 'Only update the gems in the specified group.'
complete -c bundle-update -l source --description 'The name of a :git or :path source used in the Gemfile(5).'
complete -c bundle-update -l local --description 'Do not attempt to fetch gems remotely and use the gem cache instead.'
complete -c bundle-update -l ruby --description 'Update the locked version of Ruby to the current version of Ruby.'

