# bundle-lock
# Autogenerated from man page /usr/share/man/man1/bundle-lock.1.gz
complete -c bundle-lock -l update --description 'Ignores the existing lockfile.  Resolve then updates lockfile.'
complete -c bundle-lock -l local --description 'Do not attempt to connect to rubygems. org.'
complete -c bundle-lock -l print --description 'Prints the lockfile to STDOUT instead of writing to the file system.'

