# cctiff
# Autogenerated from man page /usr/share/man/man1/cctiff.1.gz
complete -c cctiff -s v --description 'Verbose.'
complete -c cctiff -s c --description 'Combine linearisation curves into one transform.'
complete -c cctiff -s p --description 'Use slow precise correction.'
complete -c cctiff -s k --description 'Check fast result against precise, and report.'
complete -c cctiff -s r --description 'Override the default CLUT resolution.'
complete -c cctiff -s t --description 'Choose output encoding from 1. n.'
complete -c cctiff -s f --description 'Set output format to Tiff or Jpeg (Default is same as input).'
complete -c cctiff -s q --description 'Set JPEG quality 1. 100 (Default 80).'
complete -c cctiff -s a --description 'Read and Write planes > 4 as alpha planes.'
complete -c cctiff -s I --description 'Ignore any file or profile colorspace mismatches.'
complete -c cctiff -s D --description 'Don\'t append or set the output TIFF or JPEG description.'
complete -c cctiff -s e --description 'Optionally embed a profile in the destination TIFF or JPEG file.'
complete -c cctiff -s i --description 'p = perceptual, r = relative colorimetric, s = saturation, a = absolute color…'
complete -c cctiff -s o --description 'n = normal (priority: lut > matrix > monochrome) r = reverse (priority: monoc…'
complete -c cctiff -s d --description 'f = forward cal.  (default), b = backwards cal.'

