# colverify
# Autogenerated from man page /usr/share/man/man1/colverify.1.gz
complete -c colverify -s v --description 'Verbose mode, n >= 2 print each value.'
complete -c colverify -s n --description 'Normalise each files reading to its white Y.'
complete -c colverify -s N --description 'Normalise each files reading to its white XYZ.'
complete -c colverify -s m --description 'Normalise each files reading to its white X+Y+Z.'
complete -c colverify -s D --description 'Use D50 100. 0 as L*a*b* white reference.'
complete -c colverify -s c --description 'Show CIE94 delta E values.'
complete -c colverify -s k --description 'Show CIEDE2000 delta E values.'
complete -c colverify -s s --description 'Sort patch values by error.'
complete -c colverify -s w --description 'create VRML vector visualisation (measured. wrl).'
complete -c colverify -s W --description 'create VRML marker visualisation (measured. wrl).'
complete -c colverify -s x --description 'Use VRML axes.'
complete -c colverify -s f --description 'Use Fluorescent Whitening Agent compensation [opt.  simulated inst.  illum.'
complete -c colverify -s i --description 'Choose illuminant for computation of CIE XYZ from spectral data & FWA: A, C, …'
complete -c colverify -s o --description 'Choose CIE Observer for spectral data: 1931_2 (def), 1964_10, S&B 1955_2, sha…'
complete -c colverify -s L --description 'Skip any first file out of profile gamut patches.'
complete -c colverify -s X --description 'Apply Colorimeter Correction Matrix to second file.'

