# cpudist-bpfcc
# Autogenerated from man page /usr/share/man/man8/cpudist-bpfcc.8.gz
complete -c cpudist-bpfcc -s h --description 'Print usage message.'
complete -c cpudist-bpfcc -s O --description 'Measure off-CPU time instead of on-CPU time.'
complete -c cpudist-bpfcc -s T --description 'Include timestamps on output.'
complete -c cpudist-bpfcc -s m --description 'Output histogram in milliseconds.'
complete -c cpudist-bpfcc -s P --description 'Print a histogram for each PID (tgid from the kernel\'s perspective).'
complete -c cpudist-bpfcc -s L --description 'Print a histogram for each TID (pid from the kernel\'s perspective).'
complete -c cpudist-bpfcc -s p --description 'Only show this PID (filtered in kernel for efficiency).'

