# dcsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/dcsnoop-bpfcc.8.gz
complete -c dcsnoop-bpfcc -s h --description 'Print usage message.'
complete -c dcsnoop-bpfcc -s a --description 'Trace references, not just failed lookups.  EXAMPLES.'

