# diffindex-download
# Autogenerated from man page /usr/share/man/man1/diffindex-download.1.gz
complete -c diffindex-download -s n --description 'If more than number patches would be necessary, download the whole file.'
complete -c diffindex-download -s k --description 'Don\'t verify the peer certificate when using https.'
complete -c diffindex-download -s c --description 'If cacert is a directory: Use cacert as CA certificate path.'
complete -c diffindex-download -s i --description 'Don\'t exit with errror if the URL does not exist.'
complete -c diffindex-download -s q --description 'Be quiet (opposite of -v).  The default if stdout is not a terminal.'
complete -c diffindex-download -s v --description 'Be verbose (opposite of -q).  The default if stdout is a terminal.'
complete -c diffindex-download -s d --description 'Print additional debug info.'

