# docker-restart
# Autogenerated from man page /usr/share/man/man1/docker-restart.1.gz
complete -c docker-restart -l help --description '  Print usage statement.'
complete -c docker-restart -s t -l time --description '   Number of seconds to try to stop for before killing the container.'

