# docker-push
# Autogenerated from man page /usr/share/man/man1/docker-push.1.gz
complete -c docker-push -l disable-content-trust --description '  Skip image verification (default true).'
complete -c docker-push -l help --description '  Print usage statement EXAMPLES Pushing a new image to a registry.'

