# docker-network-ls
# Autogenerated from man page /usr/share/man/man1/docker-network-ls.1.gz
complete -c docker-network-ls -s f -s f --description 'The currently supported filters are: o 2 driver o 2 id (network\'s id) o 2 lab…'
complete -c docker-network-ls -l filter --description '  filter output based on conditions provided.'
complete -c docker-network-ls -l format --description '  Pretty-print networks using a Go template.    Valid placeholders:      .'
complete -c docker-network-ls -l no-trunc --description '  Do not truncate the output.'
complete -c docker-network-ls -s q -l quiet --description '  Only display network IDs.'
complete -c docker-network-ls -l help --description '  Print usage statement HISTORY.'

