# docker-search
# Autogenerated from man page /usr/share/man/man1/docker-search.1.gz
complete -c docker-search -s f -l filter --description '   Filter output based on these conditions:    - stars=<numberOfStar>    - is…'
complete -c docker-search -l help --description '  Print usage statement.'
complete -c docker-search -l limit --description '  Maximum returned search results.  The default is 25.'
complete -c docker-search -l no-trunc --description '   Don\'t truncate output.  The default is false.'

