# docker-stop
# Autogenerated from man page /usr/share/man/man1/docker-stop.1.gz
complete -c docker-stop -l help --description '  Print usage statement.'
complete -c docker-stop -s t -l time --description '  Number of seconds to wait for the container to stop before killing it.'

