# docker-images
# Autogenerated from man page /usr/share/man/man1/docker-images.1.gz
complete -c docker-images -s a -l all --description '   Show all images (by default filter out the intermediate image layers).'
complete -c docker-images -l digests --description '   Show image digests.  The default is false.'
complete -c docker-images -s f -l filter --description '   Filters the output based on these conditions:    - dangling=(true|false) -…'
complete -c docker-images -l format --description '   Pretty-print images using a Go template.     Valid placeholders:       .'
complete -c docker-images -l help --description '  Print usage statement.'
complete -c docker-images -l no-trunc --description '   Don\'t truncate output.  The default is false.'
complete -c docker-images -s q -l quiet --description '   Only show numeric IDs.  The default is false.  EXAMPLES Listing the images.'

