# docker-update
# Autogenerated from man page /usr/share/man/man1/docker-update.1.gz
complete -c docker-update -l blkio-weight --description '   Block IO weight (relative weight) accepts a weight value between 10 and 10…'
complete -c docker-update -l cpu-shares --description '   CPU shares (relative weight).'
complete -c docker-update -l cpu-period --description '   Limit the CPU CFS (Completely Fair Scheduler) period Limit the container\'s…'
complete -c docker-update -l cpu-quota --description '   Limit the CPU CFS (Completely Fair Scheduler) quota.'
complete -c docker-update -l cpu-rt-period --description '   Limit the CPU real-time period in microseconds Limit the container\'s Real …'
complete -c docker-update -l cpu-rt-runtime --description '   Limit the CPU real-time runtime in microseconds Limit the containers Real …'
complete -c docker-update -l cpuset-cpus --description '   CPUs in which to allow execution (0-3, 0,1).'
complete -c docker-update -l cpuset-mems --description '   Memory nodes(MEMs) in which to allow execution (0-3, 0,1).'
complete -c docker-update -l help --description '   Print usage statement.'
complete -c docker-update -l kernel-memory --description '   Kernel memory limit (format: <number>[<unit>], where unit = b, k, m or g) …'
complete -c docker-update -s m -l memory --description '   Memory limit (format: <number><optional unit>, where unit = b, k, m or g) …'
complete -c docker-update -l memory-reservation --description '   Memory soft limit (format: <number>[<unit>], where unit = b, k, m or g).'
complete -c docker-update -l memory-swap --description '   Total memory limit (memory + swap).'
complete -c docker-update -l restart --description '   Restart policy to apply when a container exits (no, on-failure[:max-retry]…'

