# docker-info
# Autogenerated from man page /usr/share/man/man1/docker-info.1.gz
complete -c docker-info -l help --description '  Print usage statement.'
complete -c docker-info -s f -l format --description '  Format the output using the given Go template EXAMPLES Display Docker syste…'

