# docker-wait
# Autogenerated from man page /usr/share/man/man1/docker-wait.1.gz
complete -c docker-wait -l help --description '  Print usage statement EXAMPLES $ docker run -d fedora sleep 99 079b83f558a2…'

