# docker-ps
# Autogenerated from man page /usr/share/man/man1/docker-ps.1.gz
complete -c docker-ps -s a -l all --description '   Show all containers.  Only running containers are shown by default.'
complete -c docker-ps -s f -l filter --description '   Filter output based on these conditions:    - exited=<int> an exit code of…'
complete -c docker-ps -l format --description '   Pretty-print containers using a Go template.'
complete -c docker-ps -l help --description '  Print usage statement.'
complete -c docker-ps -s l -l latest --description '   Show only the latest created container (includes all states).'
complete -c docker-ps -s n -s 1 --description '   Show n last created containers (includes all states).'
complete -c docker-ps -l no-trunc --description '   Don\'t truncate output.  The default is false.'
complete -c docker-ps -s q -l quiet --description '   Only display numeric IDs.  The default is false.'
complete -c docker-ps -s s -l size --description '   Display total file sizes.  The default is false.  EXAMPLES.'

