# docker-start
# Autogenerated from man page /usr/share/man/man1/docker-start.1.gz
complete -c docker-start -s a -l attach --description '   Attach container\'s STDOUT and STDERR and forward all signals to the    pro…'
complete -c docker-start -l detach-keys --description '   Override the key sequence for detaching a container.'
complete -c docker-start -l help --description '  Print usage statement.'
complete -c docker-start -s i -l interactive --description '   Attach container\'s STDIN.  The default is false.  See also.'

