# docker-load
# Autogenerated from man page /usr/share/man/man1/docker-load.1.gz
complete -c docker-load -l help --description '  Print usage statement.'
complete -c docker-load -s i -l input --description '   Read from a tar archive file, instead of STDIN.'
complete -c docker-load -s q -l quiet --description '   Suppress the load progress bar but still outputs the imported images.'

