# docker-version
# Autogenerated from man page /usr/share/man/man1/docker-version.1.gz
complete -c docker-version -l help --description '    Print usage statement.'
complete -c docker-version -s f -l format --description '    Format the output using the given Go template.'

