# docker-stats
# Autogenerated from man page /usr/share/man/man1/docker-stats.1.gz
complete -c docker-stats -s a -l all --description '   Show all containers.  Only running containers are shown by default.'
complete -c docker-stats -l help --description '  Print usage statement.'
complete -c docker-stats -l no-stream --description '  Disable streaming stats and only pull the first result, default setting is …'
complete -c docker-stats -l format --description '   Pretty-print containers statistics using a Go template.'

