# docker-pull
# Autogenerated from man page /usr/share/man/man1/docker-pull.1.gz
complete -c docker-pull -s a -l all-tags --description '   Download all tagged images in the repository.  The default is false.'
complete -c docker-pull -l help --description '  Print usage statement EXAMPLES Pull an image from Docker Hub.'

