# docker-exec
# Autogenerated from man page /usr/share/man/man1/docker-exec.1.gz
complete -c docker-exec -s d -l detach --description '   Detached mode: run command in the background.  The default is false.'
complete -c docker-exec -l detach-keys --description '  Override the key sequence for detaching a container.'
complete -c docker-exec -s e -l env --description '   Set environment variables This option allows you to specify arbitrary envi…'
complete -c docker-exec -l help --description '  Print usage statement.'
complete -c docker-exec -s i -l interactive --description '   Keep STDIN open even if not attached.  The default is false.'
complete -c docker-exec -l privileged --description '   Give the process extended Linux capabilities [la]http://man7.'
complete -c docker-exec -s t -l tty --description '   Allocate a pseudo-TTY.  The default is false.'
complete -c docker-exec -s u -l user --description '   Sets the username or UID used and optionally the groupname or GID for the …'

