# docker-cp
# Autogenerated from man page /usr/share/man/man1/docker-cp.1.gz
complete -c docker-cp -s L -l follow-link --description '  Follow symbol link in SRC_PATH.'
complete -c docker-cp -l help --description '  Print usage statement EXAMPLES.'

