# execsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/execsnoop-bpfcc.8.gz
complete -c execsnoop-bpfcc -s h --description 'Print usage message.'
complete -c execsnoop-bpfcc -s t --description 'Include a timestamp column.'
complete -c execsnoop-bpfcc -s x --description 'Include failed exec()s.'
complete -c execsnoop-bpfcc -s n --description 'Only print command lines matching this name (regex), matched anywhere EXAMPLE…'

