# extractttag
# Autogenerated from man page /usr/share/man/man1/extractttag.1.gz
complete -c extractttag -s v --description 'Verbose.'
complete -c extractttag -s t --description 'Extract this tag rather than default \'targ\'.'
complete -c extractttag -s c --description 'Extract calibration file from \'targ\' tag.'

