# fakeCMY
# Autogenerated from man page /usr/share/man/man1/fakeCMY.1.gz
complete -c fakeCMY -s v --description 'verbose.'
complete -c fakeCMY -s r --description 'set surface point resolution (default 3).'
complete -c fakeCMY -s l --description 'set total ink limit, 0 - 400% (estimate by default).'
complete -c fakeCMY -s L --description 'set black ink limit, 0 - 100% (estimate by default).'

