# filetop-bpfcc
# Autogenerated from man page /usr/share/man/man8/filetop-bpfcc.8.gz
complete -c filetop-bpfcc -s a --description 'Include non-regular file types (sockets, FIFOs, etc).'
complete -c filetop-bpfcc -s C --description 'Don\'t clear the screen.'
complete -c filetop-bpfcc -s r --description 'Maximum number of rows to print.  Default is 20.'
complete -c filetop-bpfcc -s p --description 'Trace this PID only.'

