# funclatency-bpfcc
# Autogenerated from man page /usr/share/man/man8/funclatency-bpfcc.8.gz
complete -c funclatency-bpfcc -s p --description 'Trace this process ID only.'
complete -c funclatency-bpfcc -s i --description 'Print output every interval seconds.'
complete -c funclatency-bpfcc -s T --description 'Include timestamps on output.'
complete -c funclatency-bpfcc -s u --description 'Output histogram in microseconds.'
complete -c funclatency-bpfcc -s m --description 'Output histogram in milliseconds.'
complete -c funclatency-bpfcc -s F --description 'Print a separate histogram per function matched.'
complete -c funclatency-bpfcc -s h --description 'Print usage message.'
complete -c funclatency-bpfcc -s r --description 'Use regular expressions for the search pattern.  EXAMPLES.'

