# funccount-bpfcc
# Autogenerated from man page /usr/share/man/man8/funccount-bpfcc.8.gz
complete -c funccount-bpfcc -s h --description 'Print usage message.'
complete -c funccount-bpfcc -s p --description 'Trace this process ID only.'
complete -c funccount-bpfcc -s i --description 'Print output every interval seconds.'
complete -c funccount-bpfcc -s T --description 'Include timestamps on output.'
complete -c funccount-bpfcc -s r --description 'Use regular expressions for the search pattern.  EXAMPLES.'

