# greytiff
# Autogenerated from man page /usr/share/man/man1/greytiff.1.gz
complete -c greytiff -s v --description 'Verbose.'
complete -c greytiff -s p --description 'Use slow precise correction.'
complete -c greytiff -s j --description 'Use CIECAM02.'

