# grip
# Autogenerated from man page /usr/share/man/man1/grip.1.gz
complete -c grip -l user-content --description 'Render as user-content like comments or issues.'
complete -c grip -l context --description 'The repository context, only taken into account when using --user-content.'
complete -c grip -l user --description 'A GitHub username for API authentication.'
complete -c grip -l pass --description 'A GitHub password or auth token for API auth.'
complete -c grip -l wide --description 'Renders wide, i. e.  when the side nav is collapsed.'
complete -c grip -l clear --description 'Clears the cached styles and assets and exits.'
complete -c grip -l export --description 'Exports to <path>. html or README.'
complete -c grip -l no-inline --description 'Link to styles instead inlining when using --export.'
complete -c grip -s b -l browser --description 'Open a tab in the browser after the server starts.'
complete -c grip -l api-url --description 'Specify a different base URL for the github API, for example that of a Github…'
complete -c grip -l title --description 'Manually sets the page\'s title.  The default is the filename.'
complete -c grip -l norefresh --description 'Do not automatically refresh the Readme content when the file changes.'
complete -c grip -l quiet --description 'Do not print to the terminal.'
complete -c grip -s V -l version --description 'Version info.'
complete -c grip -s h -l help --description 'Show help message and exit.'

