# ibus
# Autogenerated from man page /usr/share/man/man1/ibus.1.gz
complete -c ibus -l system --description 'is not given.  Show the content of the system registry cache if.'
complete -c ibus -l file --description 'is given.'

