# iccdump
# Autogenerated from man page /usr/share/man/man1/iccdump.1.gz
complete -c iccdump -s v --description 'Verbose level 1-3 (default 2).'
complete -c iccdump -s t --description 'Dump this tag only (can be used multiple times).'
complete -c iccdump -s s --description 'Search for embedded profile.'
complete -c iccdump -s i --description 'Check V4 ID value.'

