# iccgamut
# Autogenerated from man page /usr/share/man/man1/iccgamut.1.gz
complete -c iccgamut -s v --description 'Verbose.'
complete -c iccgamut -s d --description 'Surface resolution details 1. 0 - 50. 0.'
complete -c iccgamut -s w --description 'emit VRML . wrl file as well as CGATS . gam file.'
complete -c iccgamut -s n --description 'Don\'t add VRML axes or white/black point.'
complete -c iccgamut -s k --description 'Add VRML markers for prim.  & sec.  "cusp" points.'
complete -c iccgamut -s f --description 'f = forward*, b = backwards.'
complete -c iccgamut -s i --description 'p = perceptual, r = relative colorimetric, s = saturation, a = absolute (defa…'
complete -c iccgamut -s p --description 'l = Lab_PCS (default), j = CIECAM02 Appearance Jab.'
complete -c iccgamut -s o --description 'n = normal (priority: lut > matrix > monochrome) r = reverse (priority: monoc…'
complete -c iccgamut -s l --description 'set total ink limit, 0 - 400% (estimate by default).'
complete -c iccgamut -s L --description 'set black ink limit, 0 - 100% (estimate by default).'
complete -c iccgamut -s c --description 'set viewing conditions for CIECAM02, either an enumerated choice, or a series…'
complete -c iccgamut -s s --description 'Create special cube surface topology plot.'

