# icclu
# Autogenerated from man page /usr/share/man/man1/icclu.1.gz
complete -c icclu -s v --description 'Verbosity level 0 - 2 (default = 1).'
complete -c icclu -s f --description 'f = forward, b = backwards, g = gamut, p = preview.'
complete -c icclu -s i --description 'p = perceptual, r = relative colorimetric, s = saturation, a = absolute.'
complete -c icclu -s p --description 'x = XYZ_PCS, l = Lab_PCS, y = Yxy,.'
complete -c icclu -s o --description 'n = normal (priority: lut > matrix > monochrome) r = reverse (priority: monoc…'
complete -c icclu -s s --description 'Scale device range 0. 0 - scale rather than 0. 0 - 1.'

