# illumread
# Autogenerated from man page /usr/share/man/man1/illumread.1.gz
complete -c illumread -s v --description 'Verbose mode.'
complete -c illumread -s S --description 'Plot spectrum for each reading.'
complete -c illumread -s c --description 'Choose instrument from the following list (default 1) ** No ports found **.'
complete -c illumread -s N --description 'Disable initial calibration of instrument if possible.'
complete -c illumread -s H --description 'Use high resolution spectrum mode (if available).'
complete -c illumread -s Y --description 'Set refresh measurement mode.'
complete -c illumread -s W --description 'Override serial port flow control: n = none, h = HW, x = Xon/Xoff.'
complete -c illumread -s D --description 'Print debug diagnostics to stderr.'

