# intel_bios_reader
# Autogenerated from man page /usr/share/man/man1/intel_bios_reader.1.gz
complete -c intel_bios_reader -l file --description 'Parse Video BIOS Tables from FILE.'
complete -c intel_bios_reader -l devid --description 'Pretend to be PCI ID DEVID.'
complete -c intel_bios_reader -l panel-type --description 'Parse the details for flat panel N.'
complete -c intel_bios_reader -l all-panels --description 'Parse the details for all flat panels present in the Video BIOS Tables.'
complete -c intel_bios_reader -l hexdump --description 'Hex dump the blocks.'
complete -c intel_bios_reader -l block --description 'Dump only the BIOS Data Block number N.'

