# intel_panel_fitter
# Autogenerated from man page /usr/share/man/man1/intel_panel_fitter.1.gz
complete -c intel_panel_fitter -s p --description 'Pipe to be used (A, B or C, but C is only present on Ivy Bridge and newer).'
complete -c intel_panel_fitter -s x --description 'Final screen width size in pixels (needs -p option).'
complete -c intel_panel_fitter -s y --description 'Final screen height size in pixels (needs -p option).'
complete -c intel_panel_fitter -s d --description 'Disable panel fitter (needs -p option, ignores -x and -y options).'
complete -c intel_panel_fitter -s l --description 'List current state of each pipe.'
complete -c intel_panel_fitter -s h --description 'Print the help message.'

