# intel_reg
# Autogenerated from man page /usr/share/man/man1/intel_reg.1.gz
complete -c intel_reg -l verbose --description 'Increase verbosity.'
complete -c intel_reg -l quiet --description 'Decrease verbosity.'
complete -c intel_reg -l count --description 'Read N registers.'
complete -c intel_reg -l binary --description 'Output binary values.'
complete -c intel_reg -l all --description 'Decode registers for all known platforms.'
complete -c intel_reg -l mmio --description 'Use MMIO bar from FILE.'
complete -c intel_reg -l devid --description 'Pretend to be PCI ID DEVID.'
complete -c intel_reg -l spec --description 'Read register spec from directory or file specified by PATH; see REGISTER SPE…'
complete -c intel_reg -l help --description 'Show brief help.'

