# intel_gpu_top
# Autogenerated from man page /usr/share/man/man1/intel_gpu_top.1.gz
complete -c intel_gpu_top -s s --description 'Number of samples to acquire per second.'
complete -c intel_gpu_top -s o --description 'Collect usage statistics to FILE.'
complete -c intel_gpu_top -s e --description 'Execute COMMAND to profile, and leave when it is finished.'
complete -c intel_gpu_top -s h --description 'Show usage notes.'

