# invprofcheck
# Autogenerated from man page /usr/share/man/man1/invprofcheck.1.gz
complete -c invprofcheck -s v --description 'verbosity level (default 1), 2 to print each DE.'
complete -c invprofcheck -s l --description 'set total ink limit (estimate by default).'
complete -c invprofcheck -s L --description 'set black channel ink limit (estimate by default).'
complete -c invprofcheck -s h --description 'high res test (27).'
complete -c invprofcheck -s u --description 'Ultra high res test (61).'
complete -c invprofcheck -s R --description 'Specific grid resolution.'
complete -c invprofcheck -s c --description 'Show CIE94 delta E values.'
complete -c invprofcheck -s k --description 'Show CIEDE2000 delta E values.'
complete -c invprofcheck -s w --description 'create VRML visualisation (profile. wrl).'
complete -c invprofcheck -s x --description 'Use VRML axes.'
complete -c invprofcheck -s e --description 'Color vectors according to delta E.'

