# jo
# Autogenerated from man page /usr/share/man/man1/jo.1.gz
complete -c jo -s a --description 'Interpret the list of \\f[I]words\\f[] as array values and produce an array ins…'
complete -c jo -s B --description 'By default \\f[I]jo\\f[] interprets the strings "\\f[C]true\\f[]" and "\\f[C]false…'
complete -c jo -s p --description 'Pretty-print the JSON string on output instead of the terse one-line output i…'
complete -c jo -s v --description 'Show version and exit. RS . RE.'
complete -c jo -s V --description 'Show version as a JSON object and exit.'

