# killsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/killsnoop-bpfcc.8.gz
complete -c killsnoop-bpfcc -s h --description 'Print usage message.'
complete -c killsnoop-bpfcc -s x --description 'Only print failed kill() syscalls.'
complete -c killsnoop-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).  EXAMPLES.'

