# kodak2ti3
# Autogenerated from man page /usr/share/man/man1/kodak2ti3.1.gz
complete -c kodak2ti3 -s v --description 'Verbose mode.'
complete -c kodak2ti3 -s l --description 'set ink limit, 0 - 400%.'
complete -c kodak2ti3 -s r --description 'Use an alternate 928 patch reference file.'

