# lvm-fullreport
# Autogenerated from man page /usr/share/man/man8/lvm-fullreport.8.gz
complete -c lvm-fullreport -l all --description 'Include information in the output about internal Logical Volumes that are com…'
complete -c lvm-fullreport -l aligned --description 'Use with --separator to align the output columns.'
complete -c lvm-fullreport -l binary --description 'Use binary values "0" or "1" instead of descriptive literal values for column…'
complete -c lvm-fullreport -l configreport --description 'Make any subsequent -o, --options, -O, --sort or -S, --select to apply for Re…'
complete -c lvm-fullreport -l logonly --description 'Suppress the main report itself and display only log report on output.'
complete -c lvm-fullreport -l nameprefixes --description 'Add an "LVM2_" prefix plus the field name to the output.'
complete -c lvm-fullreport -l noheadings --description 'Suppress the headings line that is normally the first line of output.'
complete -c lvm-fullreport -l nosuffix --description 'Suppress the suffix on output sizes.'
complete -c lvm-fullreport -s o -l options --description 'Comma-separated ordered list of columns.'
complete -c lvm-fullreport -s O -l sort --description 'Comma-separated ordered list of columns to sort by.'
complete -c lvm-fullreport -l rows --description 'Output columns as rows.'
complete -c lvm-fullreport -s S -l select --description 'Display only rows that match Selection criteria.'
complete -c lvm-fullreport -l separator --description 'String to use to separate each column.   Useful if grepping the output.'
complete -c lvm-fullreport -l unbuffered --description 'Produce output immediately without sorting or aligning the columns properly.'
complete -c lvm-fullreport -l units --description 'All sizes are output in these units: (h)uman-readable, (b)ytes, (s)ectors, (k…'
complete -c lvm-fullreport -l unquoted --description 'When used with --nameprefixes, output values in the field=value pairs are not…'

