# mailutils
# Autogenerated from man page /usr/share/man/man1/mailutils.1.gz
complete -c mailutils -l debug-level --description 'set Mailutils debugging level.'
complete -c mailutils -l debug-line-info --description 'show source info with debugging messages P Informational options.'
complete -c mailutils -l show-config-options --description 'show compilation options.'
complete -c mailutils -s '?' -l help --description 'give this help list.'
complete -c mailutils -l usage --description 'give a short usage message.'
complete -c mailutils -s V -l version --description 'print program version.'

