# mailx
# Autogenerated from man page /usr/share/man/man1/mailx.1.gz
complete -c mailx -s a --description 'Specify additional header fields on the command line such as "X-Loop: foo@bar…'
complete -c mailx -s b --description 'Send blind carbon copies to bcc-addr.'
complete -c mailx -s c --description 'Send carbon copies to list of users.'
complete -c mailx -s d --description 'Causes mailx mail to output all sorts of information useful for debugging mai…'
complete -c mailx -s E --description 'Don\'t send messages with an empty body.'
complete -c mailx -s f --description 'Use an alternate mailbox.'
complete -c mailx -s I --description 'Forces mailx mail to run in interactive mode, even when input is not a termin…'
complete -c mailx -s i --description 'Ignore tty interrupt signals.'
complete -c mailx -s N --description 'Inhibits initial display of message headers when reading mail or editing a ma…'
complete -c mailx -s n --description 'Inhibits reading /etc/mail. rc upon startup.'
complete -c mailx -s r --description 'Use from-addr as the from address in the message and envelope.'
complete -c mailx -s s --description 'Specify subject on command line (only the first argument after the s flag is …'
complete -c mailx -s u --description 'Equivalent to: Pp $ mail -f /var/mail/user Pp except that locking is done.'
complete -c mailx -s v --description 'Verbose mode.  The details of delivery are displayed on the user\'s terminal.'

