# memleak-bpfcc
# Autogenerated from man page /usr/share/man/man8/memleak-bpfcc.8.gz
complete -c memleak-bpfcc -s h --description 'Print usage message.'
complete -c memleak-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).'
complete -c memleak-bpfcc -s t --description 'Print a trace of all allocation and free requests and results.'
complete -c memleak-bpfcc -s a --description 'Print a list of allocations that weren\'t freed (and their sizes) in addition …'
complete -c memleak-bpfcc -s o --description 'Print only allocations older than OLDER milliseconds.'
complete -c memleak-bpfcc -s c --description 'Run the specified command and trace its allocations only.'
complete -c memleak-bpfcc -s s --description 'Record roughly every SAMPLE_RATE-th allocation to reduce overhead.'
complete -c memleak-bpfcc -s z --description 'Capture only allocations that are larger than or equal to MIN_SIZE bytes.'
complete -c memleak-bpfcc -s Z --description 'Capture only allocations that are smaller than or equal to MAX_SIZE bytes.'

