# ModemManager
# Autogenerated from man page /usr/share/man/man8/ModemManager.8.gz
complete -c ModemManager -s V -l version --description 'Print the ModemManager software version and exit.'
complete -c ModemManager -s h -l help --description 'Show application options.'
complete -c ModemManager -l help-all --description 'Show application and test options.'
complete -c ModemManager -l help-test --description 'Show test options.'
complete -c ModemManager -l debug --description 'Runs ModemManager with "DEBUG" log level and without daemonizing.'
complete -c ModemManager -l log-level --description 'Sets how much information ModemManager sends to the log destination (usually …'
complete -c ModemManager -l log-file --description 'Specify location of the file where ModemManager will dump its log messages, i…'
complete -c ModemManager -l timestamps --description 'Include absolute timestamps in the log output.'
complete -c ModemManager -l relative-timestamps --description 'Include timestamps, relative to the start time of the daemon, in the log outp…'
complete -c ModemManager -l test-session --description 'Run the ModemManager daemon in the Session bus instead of the System bus.'
complete -c ModemManager -l test-no-auto-scan --description 'Fully disable udev-based auto-scan looking for devices.'
complete -c ModemManager -l test-enable --description 'Enable the Test DBus interface in the daemon.'
complete -c ModemManager -l test-plugin-dir --description 'Specify an alternate directory where the daemon should look for vendor plugin…'

