# mppcheck
# Autogenerated from man page /usr/share/man/man1/mppcheck.1.gz
complete -c mppcheck -s v --description 'Verbose mode.'
complete -c mppcheck -s c --description 'Show CIE94 delta E values.'
complete -c mppcheck -s k --description 'Show CIEDE2000 delta E values.'
complete -c mppcheck -s s --description 'Check spectral model too.'
complete -c mppcheck -s y --description 'Detail each value.'

