# mpplu
# Autogenerated from man page /usr/share/man/man1/mpplu.1.gz
complete -c mpplu -s v --description 'Verbose.'
complete -c mpplu -s f --description 'f = forward, b = backwards.'
complete -c mpplu -s p --description 'x = XYZ_PCS, l = Lab_PCS, y = Yxy, s = spectral,.'
complete -c mpplu -s l --description 'override default ink limit, 1 - N00%.'
complete -c mpplu -s i --description 'Choose illuminant for print/transparency spectral data: A, C, D50 (def.'
complete -c mpplu -s o --description 'Choose CIE Observer for spectral data: 1931_2 (def), 1964_10, S&B 1955_2, sha…'
complete -c mpplu -s u --description 'Use Fluorescent Whitening Agent compensation.'
complete -c mpplu -s g --description 'Create gamut output.'
complete -c mpplu -s w --description 'Create gamut VRML as well.'
complete -c mpplu -s n --description 'Don\'t add VRML axes.'
complete -c mpplu -s a --description 'Gamut transparency level.'
complete -c mpplu -s d --description 'Gamut surface detail level.'
complete -c mpplu -s t --description 'Invoke debugging test code "num" 1.'

