# mppprof
# Autogenerated from man page /usr/share/man/man1/mppprof.1.gz
complete -c mppprof -s v --description '.'
complete -c mppprof -s q --description '.'
complete -c mppprof -s l --description 'override default ink limit, 1 - n00%.'
complete -c mppprof -s s --description 'Generate spectral model too.'
complete -c mppprof -s m --description 'Generate ink mixing model.'
complete -c mppprof -s y --description '.'
complete -c mppprof -s L --description 'Output Lab values.'

