# netstat-nat
# Autogenerated from man page /usr/share/man/man1/netstat-nat.1.gz
complete -c netstat-nat -s h --description 'displays help.'
complete -c netstat-nat -s n --description 'don\'t resolve IPs/portnumbers to host/portnames.'
complete -c netstat-nat -s p --description 'display NAT connections with protocol selection (see /etc/protocols).'
complete -c netstat-nat -s s --description 'display connections by source IP/hostname.'
complete -c netstat-nat -s d --description 'display connections by destination IP/hostname.'
complete -c netstat-nat -s S --description 'display SNAT connections.'
complete -c netstat-nat -s D --description 'display DNAT connections.'
complete -c netstat-nat -s L --description 'display only connections to NAT box self (doesn\'t show SNAT & DNAT).'
complete -c netstat-nat -s R --description 'display only connections routed through the NAT box (doesn\'t show SNAT & DNAT…'
complete -c netstat-nat -s x --description 'extended view of hostnames.'
complete -c netstat-nat -s r --description 'sort connections.'
complete -c netstat-nat -s o --description 'no output header.'
complete -c netstat-nat -s N --description 'display NAT box connection information (only valid with SNAT & DNAT).'
complete -c netstat-nat -s v --description 'prints version FILES /proc/net/ip_conntrack or /proc/net/nf_conntrack  SEE AL…'

