# nicstat
# Autogenerated from man page /usr/share/man/man1/nicstat.1.gz
complete -c nicstat -s h --description 'Display brief usage information (help).'
complete -c nicstat -s v --description 'Display nicstat version (and additional fields when combined with \'-l\').'
complete -c nicstat -s n --description 'Show statistics for non-local (i. e.  non-loopback) interfaces only.'
complete -c nicstat -s s --description 'Display summary output - just the amount of data received (read) and transmit…'
complete -c nicstat -s x --description 'Display extended output.   See OUTPUT section for details.'
complete -c nicstat -s U --description 'Display separate read and write utilization statistics.'
complete -c nicstat -s M --description 'Display interface throughput statistics in Mbps (megabits per second), instea…'
complete -c nicstat -s p --description 'Display output in parseable format.'
complete -c nicstat -s z --description 'Skip interfaces for which there was zero traffic for the sample period.'
complete -c nicstat -s t --description 'Show TCP statistics.'
complete -c nicstat -s u --description 'Show UDP statistics.'
complete -c nicstat -s a --description 'Equvalent to \'-x -t -u\'.'
complete -c nicstat -s l --description 'Just list interfaces.'
complete -c nicstat -s i --description 'Show statistics for only the interface(s) listed.'
complete -c nicstat -s S --description '(Linux only).'
complete -c nicstat -s k --description '(Solaris only).'

