# npm-install
# Autogenerated from man page /usr/share/man/man1/npm-install.1.gz
complete -c npm-install -s S -l save: --description '.'
complete -c npm-install -s D -l save-dev: --description '.'
complete -c npm-install -s O -l save-optional: --description '.'
complete -c npm-install -s E -l save-exact: --description '.'

