# npm-uninstall
# Autogenerated from man page /usr/share/man/man1/npm-uninstall.1.gz
complete -c npm-uninstall -s S -l save: --description '.'
complete -c npm-uninstall -s D -l save-dev: --description '.'
complete -c npm-uninstall -s O -l save-optional: --description '.'

