# oeminst
# Autogenerated from man page /usr/share/man/man1/oeminst.1.gz
complete -c oeminst -s v --description 'Verbose.'
complete -c oeminst -s n --description 'Don\'t install, show where files would be installed.'
complete -c oeminst -s c --description 'Don\'t install, save files to current directory.'
complete -c oeminst -s S --description 'Specify the install scope u = user (def. ), l = local system].'

