# offcputime-bpfcc
# Autogenerated from man page /usr/share/man/man8/offcputime-bpfcc.8.gz
complete -c offcputime-bpfcc -s h --description 'Print usage message.'
complete -c offcputime-bpfcc -s f --description 'Print output in folded stack format.'
complete -c offcputime-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).'
complete -c offcputime-bpfcc -s t --description 'Trace this thread ID only (filtered in-kernel).'
complete -c offcputime-bpfcc -s u --description 'Only trace user threads (no kernel threads).'
complete -c offcputime-bpfcc -s k --description 'Only trace kernel threads (no user threads).'
complete -c offcputime-bpfcc -s U --description 'Show stacks from user space only (no kernel space stacks).'
complete -c offcputime-bpfcc -s K --description 'Show stacks from kernel space only (no user space stacks).'
complete -c offcputime-bpfcc -s d --description 'Insert delimiter between kernel/user stacks.'
complete -c offcputime-bpfcc -l stack-storage-size --description 'Change the number of unique stack traces that can be stored and displayed.'

