# offwaketime-bpfcc
# Autogenerated from man page /usr/share/man/man8/offwaketime-bpfcc.8.gz
complete -c offwaketime-bpfcc -s h --description 'Print usage message.'
complete -c offwaketime-bpfcc -s f --description 'Output stacks in folded format.'
complete -c offwaketime-bpfcc -s u --description 'Only trace user threads (not kernel threads).'
complete -c offwaketime-bpfcc -s v --description 'Show raw addresses for non-folded mode.'
complete -c offwaketime-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).'

