# opensnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/opensnoop-bpfcc.8.gz
complete -c opensnoop-bpfcc -s h --description 'Print usage message.'
complete -c opensnoop-bpfcc -s t --description 'Include a timestamp column.'
complete -c opensnoop-bpfcc -s x --description 'Only print failed opens.'
complete -c opensnoop-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).  EXAMPLES.'

