# perf-timechart
# Autogenerated from man page /usr/share/man/man1/perf-timechart.1.gz
complete -c perf-timechart -s o -l output --description '.'
complete -c perf-timechart -s i -l input --description '.'
complete -c perf-timechart -s w -l width --description '.'
complete -c perf-timechart -s P -l power-only --description '.'
complete -c perf-timechart -s T -l tasks-only --description '.'
complete -c perf-timechart -s p -l process --description '.'
complete -c perf-timechart -l symfs --description '.'
complete -c perf-timechart -s n -l proc-num --description '.'
complete -c perf-timechart -s t -l topology --description '.'
complete -c perf-timechart -l highlight --description '.'
complete -c perf-timechart -l io-skip-eagain --description '.'
complete -c perf-timechart -l io-min-time --description '.'
complete -c perf-timechart -l io-merge-dist --description '.'
complete -c perf-timechart -s I -l io-only --description '.'
complete -c perf-timechart -s g -l callchain --description '.'

