# perf
# Autogenerated from man page /usr/share/man/man1/perf.1.gz
complete -c perf -l debug --description 'Setup debug variable (see list below) in value range (0, 10).'
complete -c perf -l buildid-dir --description 'Setup buildid cache directory.  It has higher priority than buildid.'
complete -c perf -s v -l version --description 'Display perf version.'
complete -c perf -s h -l help --description 'Run perf help command.'

