# perf-buildid-cache
# Autogenerated from man page /usr/share/man/man1/perf-buildid-cache.1.gz
complete -c perf-buildid-cache -s a -l add --description 'Add specified file to the cache.'
complete -c perf-buildid-cache -s k -l kcore --description 'Add specified kcore file to the cache.'
complete -c perf-buildid-cache -s r -l remove --description 'Remove a cached binary which has same build-id of specified file from the cac…'
complete -c perf-buildid-cache -s p -l purge --description 'Purge all cached binaries including older caches which have specified path fr…'
complete -c perf-buildid-cache -s M -l missing --description 'List missing build ids in the cache for the specified file.'
complete -c perf-buildid-cache -s u -l update --description 'Update specified file of the cache.'
complete -c perf-buildid-cache -s v -l verbose --description 'Be more verbose.'

