# perf-test
# Autogenerated from man page /usr/share/man/man1/perf-test.1.gz
complete -c perf-test -s s -l skip --description 'Tests to skip (comma separated numeric list).'
complete -c perf-test -s v -l verbose --description 'Be more verbose.'
complete -c perf-test -s F -l dont-fork --description 'Do not fork child for each test, run all tests within single process.'

