# perf-inject
# Autogenerated from man page /usr/share/man/man1/perf-inject.1.gz
complete -c perf-inject -s b -l build-ids --description 'Inject build-ids into the output stream.'
complete -c perf-inject -s v -l verbose --description 'Be more verbose.'
complete -c perf-inject -s i -l input --description 'Input file name.  (default: stdin).'
complete -c perf-inject -s o -l output --description 'Output file name.  (default: stdout).'
complete -c perf-inject -s s -l sched-stat --description 'Merge sched_stat and sched_switch for getting events where and how long tasks…'
complete -c perf-inject -l kallsyms --description 'kallsyms pathname.'
complete -c perf-inject -l itrace --description 'Decode Instruction Tracing data, replacing it with synthesized events.'
complete -c perf-inject -l strip --description 'Use with --itrace to strip out non-synthesized events.'
complete -c perf-inject -s j -l jit --description 'Process jitdump files by injecting the mmap records corresponding to jitted f…'

