# perf-evlist
# Autogenerated from man page /usr/share/man/man1/perf-evlist.1.gz
complete -c perf-evlist -s i -l input --description 'Input file name.  (default: perf. data unless stdin is a fifo).'
complete -c perf-evlist -s F -l freq --description 'Show just the sample frequency used for each event.'
complete -c perf-evlist -s v -l verbose --description 'Show all fields.'
complete -c perf-evlist -s g -l group --description 'Show event group information.'
complete -c perf-evlist -l trace-fields --description 'Show tracepoint field names.'

