# perf-config
# Autogenerated from man page /usr/share/man/man1/perf-config.1.gz
complete -c perf-config -s l -l list --description 'Show current config variables, name and value, for all sections.'
complete -c perf-config -l user --description 'For writing and reading options: write to user $HOME/.'
complete -c perf-config -l system --description 'For writing and reading options: write to system-wide $(sysconfdir)/perfconfi…'
complete -c perf-config -l slab --description 'nor.'
complete -c perf-config -l page --description 'option is used.  Default is slab.  record. *, record. build-id.'

