# perf-mem
# Autogenerated from man page /usr/share/man/man1/perf-mem.1.gz
complete -c perf-mem -s t -l type --description 'Select the memory operation type: load or store (default: load,store).'
complete -c perf-mem -s D -l dump-raw-samples --description 'Dump the raw decoded samples on the screen in a format that is easy to parse …'
complete -c perf-mem -s x -l field-separator --description 'Specify the field separator used when dump raw samples (-D option).'
complete -c perf-mem -s C -l cpu-list --description 'Restrict dump of raw samples to those provided via this option.'
complete -c perf-mem -s K -l all-kernel --description 'Configure all used events to run in kernel space.'
complete -c perf-mem -s U -l all-user --description 'Configure all used events to run in user space.'
complete -c perf-mem -l ldload --description 'Specify desired latency for loads event.'

