# perf-list
# Autogenerated from man page /usr/share/man/man1/perf-list.1.gz
complete -c perf-list -l no-desc --description 'Don\\(cqt print descriptions.'
complete -c perf-list -s v -l long-desc --description 'Print longer event descriptions.'
complete -c perf-list -l raw-dump --description ' 2. c   2.  4. 2.'

