# perf-lock
# Autogenerated from man page /usr/share/man/man1/perf-lock.1.gz
complete -c perf-lock -s i -l input --description '.'
complete -c perf-lock -s v -l verbose --description '.'
complete -c perf-lock -s D -l dump-raw-trace --description '.'
complete -c perf-lock -s k -l key --description '.'
complete -c perf-lock -s t -l threads --description '.'
complete -c perf-lock -s m -l map --description '.'

