# perf-buildid-list
# Autogenerated from man page /usr/share/man/man1/perf-buildid-list.1.gz
complete -c perf-buildid-list -s H -l with-hits --description 'Show only DSOs with hits.'
complete -c perf-buildid-list -s i -l input --description 'Input file name.  (default: perf. data unless stdin is a fifo).'
complete -c perf-buildid-list -s f -l force --description 'Don\\(cqt do ownership validation.'
complete -c perf-buildid-list -s k -l kernel --description 'Show running kernel build id.'
complete -c perf-buildid-list -s v -l verbose --description 'Be more verbose.'

