# perf-data
# Autogenerated from man page /usr/share/man/man1/perf-data.1.gz
complete -c perf-data -l to-ctf --description '.'
complete -c perf-data -s i --description '.'
complete -c perf-data -s v -l verbose --description '.'
complete -c perf-data -l all --description '.'

