# profcheck
# Autogenerated from man page /usr/share/man/man1/profcheck.1.gz
complete -c profcheck -s v --description 'Verbosity level (default 1), 2 to print each DE.'
complete -c profcheck -s c --description 'Show CIE94 delta E values.'
complete -c profcheck -s k --description 'Show CIEDE2000 delta E values.'
complete -c profcheck -s w --description 'create VRML visualisation (iccprofile. wrl).'
complete -c profcheck -s x --description 'Use VRML axes.'
complete -c profcheck -s m --description 'Make VRML lines a minimum of 0. 5.'
complete -c profcheck -s e --description 'Color vectors according to delta E.'
complete -c profcheck -s d --description 'Specify a device value to sort against.'
complete -c profcheck -s p --description 'Sort device value by PCS (Lab) target.'
complete -c profcheck -s f --description 'Use Fluorescent Whitening Agent compensation [opt.  simulated inst.  illum.'
complete -c profcheck -s i --description 'Choose illuminant for computation of CIE XYZ from spectral data & FWA: A, C, …'
complete -c profcheck -s o --description 'Choose CIE Observer for spectral data: 1931_2 (def), 1964_10, S&B 1955_2, sha…'
complete -c profcheck -s I --description 'r = relative colorimetric, a = absolute (default).'

