# profile-bpfcc
# Autogenerated from man page /usr/share/man/man8/profile-bpfcc.8.gz
complete -c profile-bpfcc -s h --description 'Print usage message.'
complete -c profile-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).'
complete -c profile-bpfcc -s F --description 'Frequency to sample stacks (default 49).'
complete -c profile-bpfcc -s f --description 'Print output in folded stack format.'
complete -c profile-bpfcc -s d --description 'Include an output delimiter between kernel and user stacks (either "--", or, …'
complete -c profile-bpfcc -s U --description 'Show stacks from user space only (no kernel space stacks).'
complete -c profile-bpfcc -s K --description 'Show stacks from kernel space only (no user space stacks).'
complete -c profile-bpfcc -l stack-storage-size --description 'The maximum number of unique stack traces that the kernel will count (default…'
complete -c profile-bpfcc -s S --description 'A fixed number of kernel frames to skip.'

