# pry
# Autogenerated from man page /usr/share/man/man1/pry.1.gz
complete -c pry -s v -l version --description 'Prints the version of Pry.'
complete -c pry -s e -l exec --description 'Executes argument in context before the session starts.'
complete -c pry -l no-pager --description 'Disable pager for long output.'
complete -c pry -l no-history --description 'Disable history loading.'
complete -c pry -l no-color --description 'Disable syntax highlighting for session.'
complete -c pry -s f --description 'Prevent loading of ~/. pryrc for session.'
complete -c pry -l no-plugins --description 'Suppress loading of plugins.'
complete -c pry -l installed-plugins --description 'List installed plugins.'
complete -c pry -l simple-prompt --description 'Enable simple prompt mode (eg, >>).'
complete -c pry -s r -l require --description 'Require a ruby script at startup.'
complete -c pry -s I --description 'Add a path to the $LOAD_PATH .'

