# refine
# Autogenerated from man page /usr/share/man/man1/refine.1.gz
complete -c refine -s v --description 'Verbose.'
complete -c refine -s c --description 'Create initial abstract correction profile.'
complete -c refine -s g --description 'Don\'t impose output device gamut limit.'
complete -c refine -s r --description 'Set abstract profile clut resolution (default 33).'
complete -c refine -s d --description 'Override default damping factor (default 0. 950000, then 0. 700000).'
complete -c refine -s R --description 'Aim for white point relative match rather than absolute.'
complete -c refine -s f --description 'Use Fluorescent Whitening Agent compensation [opt.  simulated inst.  illum.'
complete -c refine -s i --description 'Choose illuminant for computation of CIE XYZ from spectral data & FWA: A, C, …'
complete -c refine -s o --description 'Choose CIE Observer for spectral data: 1931_2 (def), 1964_10, S&B 1955_2, sha…'

