# regexp-assemble
# Autogenerated from man page /usr/share/man/man1/regexp-assemble.1p.gz
complete -c regexp-assemble -s a --description 'look Ahead.  Insert \\f(CW\\*(C`(?=.'
complete -c regexp-assemble -s b --description 'Blank.  Ignore blank lines.'
complete -c regexp-assemble -s c --description 'Comment.  Basic comment filtering.'
complete -c regexp-assemble -s d --description 'Debug.  Turns on debugging output.  See Regexp::Assemble for suitable values.'
complete -c regexp-assemble -s i --description 'Indent.'
complete -c regexp-assemble -s n --description 'No newline.  Do not print a newline after the pattern.'
complete -c regexp-assemble -s p --description 'Print.  Print the pattern.'
complete -c regexp-assemble -s r --description 'Reduce.  The default behaviour is to reduce the assembled pattern.'
complete -c regexp-assemble -s s --description 'Statistics.  Print some statistics about the assembled pattern.'
complete -c regexp-assemble -s S --description 'Statistics only.  Like -s, except that the pattern itself is not output.'
complete -c regexp-assemble -s t --description 'Test.  Test the assembled expression against the contents of a file.'
complete -c regexp-assemble -s T --description 'Time.  Print statistics on the time taken to reduce and assemble the pattern.'
complete -c regexp-assemble -s u --description 'Unique.  Carp if duplicate patterns are found.'
complete -c regexp-assemble -s U --description 'Unroll.'
complete -c regexp-assemble -s v --description 'Version.  Print the version of the regexp-assemble script.'

