# revfix
# Autogenerated from man page /usr/share/man/man1/revfix.1.gz
complete -c revfix -s v --description 'Verbose.'
complete -c revfix -s 0 --description 'Process perceptual.'
complete -c revfix -s 1 --description 'Process absolute/relative colorimetric.'
complete -c revfix -s 2 --description 'Process saturation.'
complete -c revfix -s r --description 'Override BtoA1 Clut res.'
complete -c revfix -s k --description 'e = same K as existing BtoA table (def) z = zero, h = 0.'
complete -c revfix -s K --description 'Same as -k, but target is K locus rather than K value itself.'
complete -c revfix -s l --description 'set total ink limit, 0 - 400% (estimate by default).'
complete -c revfix -s L --description 'set black ink limit, 0 - 100% (estimate by default).'
complete -c revfix -s p --description 'Include abstract profile in output tables.'

