# runc-restore
# Autogenerated from man page /usr/share/man/man8/runc-restore.8.gz
complete -c runc-restore -l image-path --description '   --work-path value            path for saving work files and logs    --tcp-…'

