# runc-checkpoint
# Autogenerated from man page /usr/share/man/man8/runc-checkpoint.8.gz
complete -c runc-checkpoint -l image-path --description '   --work-path value            path for saving work files and logs    --leav…'

