# runc-create
# Autogenerated from man page /usr/share/man/man8/runc-create.8.gz
complete -c runc-create -l bundle -s b --description '   --console value           specify the pty slave path for use with the cont…'

