# runc-exec
# Autogenerated from man page /usr/share/man/man8/runc-exec.8.gz
complete -c runc-exec -l console --description '   --cwd value                  current working directory in the container   …'

