# runc-run
# Autogenerated from man page /usr/share/man/man8/runc-run.8.gz
complete -c runc-run -l bundle -s b --description '   --console value           specify the pty slave path for use with the cont…'

