# runc-update
# Autogenerated from man page /usr/share/man/man8/runc-update.8.gz
complete -c runc-update -l resources -s r --description '   --blkio-weight value         Specifies per cgroup weight, range is from 10…'

