# runc-events
# Autogenerated from man page /usr/share/man/man8/runc-events.8.gz
complete -c runc-events -l interval --description '   --stats              display the container\'s stats then exit.'

