# runqlat-bpfcc
# Autogenerated from man page /usr/share/man/man8/runqlat-bpfcc.8.gz
complete -c runqlat-bpfcc -s h --description 'Print usage message.'
complete -c runqlat-bpfcc -s T --description 'Include timestamps on output.'
complete -c runqlat-bpfcc -s m --description 'Output histogram in milliseconds.'
complete -c runqlat-bpfcc -s P --description 'Print a histogram for each PID.'
complete -c runqlat-bpfcc -s p --description 'Only show this PID (filtered in kernel for efficiency).'

