# scanin
# Autogenerated from man page /usr/share/man/man1/scanin.1.gz
complete -c scanin -s g --description ':- outputs file \'recogout. cht\', or.'
complete -c scanin -s o --description ':- outputs file \'input. val\', or.'
complete -c scanin -s c --description ':- inputs pbase. ti2 and outputs printer pbase. ti3, or.'
complete -c scanin -s r --description ':- inputs pbase. ti2+. ti3 and outputs pbase. ti3.'
complete -c scanin -o ca --description 'Same as -c, but accumulates more values to pbase . ti3 from subsequent pages.'
complete -c scanin -s F --description 'Don\'t auto recognize, locate using four fiducual marks.'
complete -c scanin -s p --description 'Compensate for perspective distortion.'
complete -c scanin -s a --description 'Recognise chart in normal orientation only (-A fallback as is) Default is to …'
complete -c scanin -s m --description 'Return true mean (default is robust mean).'
complete -c scanin -s G --description 'Approximate gamma encoding of image.'
complete -c scanin -s v --description 'Verbosity level 0-9.'
complete -c scanin -s d --description 'Generate diagnostic output (try -dipn).'
complete -c scanin -s O --description '.'

