# shellcheck
# Autogenerated from man page /usr/share/man/man1/shellcheck.1.gz
complete -c shellcheck -s s --description 'POSIX compliant (similar to checkbashisms).'
complete -c shellcheck -s C -l color --description 'For TTY output, enable colors always, never or auto.  The default is auto.'
complete -c shellcheck -s e -l exclude --description 'Explicitly exclude the specified codes from the report.'
complete -c shellcheck -s f -l format --description 'Specify the output format of shellcheck, which prints its results in the stan…'
complete -c shellcheck -l shell --description 'Specify Bourne shell dialect.  Valid values are sh, bash, dash and ksh.'
complete -c shellcheck -s V -l version --description 'Print version information and exit.'
complete -c shellcheck -s x -l external-sources --description 'Follow [aq]source[aq] statements even when the file is not specified as input.'

