# softirqs-bpfcc
# Autogenerated from man page /usr/share/man/man8/softirqs-bpfcc.8.gz
complete -c softirqs-bpfcc -s h --description 'Print usage message.'
complete -c softirqs-bpfcc -s T --description 'Include timestamps on output.'
complete -c softirqs-bpfcc -s N --description 'Output in nanoseconds.'
complete -c softirqs-bpfcc -s d --description 'Show IRQ time distribution as histograms EXAMPLES.'

