# specplot
# Autogenerated from man page /usr/share/man/man1/specplot.1.gz
complete -c specplot -s v --description 'verbose.'
complete -c specplot -s c --description 'combine multiple files into one plot.'
complete -c specplot -s z --description 'don\'t make range cover zero.'
complete -c specplot -s u --description 'plot effect of adding estimated UV level.'
complete -c specplot -s U --description 'plot effect of adding range of estimated UV level.'

