# spec2cie
# Autogenerated from man page /usr/share/man/man1/spec2cie.1.gz
complete -c spec2cie -s v --description 'Verbose mode.'
complete -c spec2cie -s I --description 'Override actual instrument illuminant in .'
complete -c spec2cie -s f --description 'Use Fluorescent Whitening Agent compensation [simulated inst.  illum.'
complete -c spec2cie -s i --description 'Choose illuminant for computation of CIE XYZ from spectral data & FWA: A, C, …'
complete -c spec2cie -s o --description 'Choose CIE Observer for spectral data: 1931_2 (def), 1964_10, S&B 1955_2, sha…'
complete -c spec2cie -s n --description 'Don\'t output spectral values.'
complete -c spec2cie -s p --description 'Plot each values spectrum.'

