# splitti3
# Autogenerated from man page /usr/share/man/man1/splitti3.1.gz
complete -c splitti3 -s v --description 'Verbose - print each patch value.'
complete -c splitti3 -s n --description 'Put no sets in first file, and balance in second file.'
complete -c splitti3 -s p --description 'Put percent% sets in first file, and balance in second file.  (def.  50%).'
complete -c splitti3 -s w --description 'Put white patches in both files.'
complete -c splitti3 -s r --description 'Use given random seed.'

