# stacksnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/stacksnoop-bpfcc.8.gz
complete -c stacksnoop-bpfcc -s h --description 'Print usage message.'
complete -c stacksnoop-bpfcc -s s --description 'Show address offsets.'
complete -c stacksnoop-bpfcc -s v --description 'Print more fields.'
complete -c stacksnoop-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).'

