# stackcount-bpfcc
# Autogenerated from man page /usr/share/man/man8/stackcount-bpfcc.8.gz
complete -c stackcount-bpfcc -s h --description 'Print usage message.'
complete -c stackcount-bpfcc -s r --description 'Allow regular expressions for the search pattern.'
complete -c stackcount-bpfcc -s s --description 'Show address offsets.'
complete -c stackcount-bpfcc -s T --description 'Include a timestamp with interval output.'
complete -c stackcount-bpfcc -s v --description 'Show raw addresses.'
complete -c stackcount-bpfcc -s i --description 'Summary interval, in seconds.'
complete -c stackcount-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).'

