# statsnoop-bpfcc
# Autogenerated from man page /usr/share/man/man8/statsnoop-bpfcc.8.gz
complete -c statsnoop-bpfcc -s h --description 'Print usage message.'
complete -c statsnoop-bpfcc -s t --description 'Include a timestamp column.'
complete -c statsnoop-bpfcc -s x --description 'Only print failed stats.'
complete -c statsnoop-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).  EXAMPLES.'

