# synthcal
# Autogenerated from man page /usr/share/man/man1/synthcal.1.gz
complete -c synthcal -s t --description 'i = input, o = output, d = display (default).'
complete -c synthcal -s d --description 'choose colorant combination from the following (default 3): 0: Print grey 1: …'
complete -c synthcal -s D --description 'Add or delete colorant from combination: (Use -?? to list known colorants).'
complete -c synthcal -s o --description 'Set non-linear curve offset (default 0. 0).'
complete -c synthcal -s s --description 'Set non-linear curve scale (default 1. 0).'
complete -c synthcal -s p --description 'Set non-linear curve powers (default 1. 0).'
complete -c synthcal -s E --description 'Set the profile dEscription string.'

