# synthread
# Autogenerated from man page /usr/share/man/man1/synthread.1.gz
complete -c synthread -s v --description 'Verbose mode.'
complete -c synthread -s p --description 'Use separation profile.'
complete -c synthread -s l --description 'Construct and output in Lab rather than XYZ.'
complete -c synthread -s i --description 'Set input channel curve powers (default 1. 0).'
complete -c synthread -s k --description 'Set input channel inflection points (default 0. 5,0. 5).'
complete -c synthread -s o --description 'Set output channel curve powers (default 1. 0).'
complete -c synthread -s r --description 'Add average random deviation of <level>% to input device values (after sep. ).'
complete -c synthread -s R --description 'Add average random deviation of <level>% to output PCS values.'
complete -c synthread -s u --description 'Make random deviations have uniform distributions rather than normal.'
complete -c synthread -s b --description 'Scale black point to target Lab value.'

