# tcpaccept-bpfcc
# Autogenerated from man page /usr/share/man/man8/tcpaccept-bpfcc.8.gz
complete -c tcpaccept-bpfcc -s h --description 'Print usage message.'
complete -c tcpaccept-bpfcc -s t --description 'Include a timestamp column.'
complete -c tcpaccept-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).  EXAMPLES.'

