# terminix
# Autogenerated from man page /usr/share/man/man1/terminix.1.gz
complete -c terminix -s h -l help --description 'Show help options.'
complete -c terminix -s v -l version --description 'Shows the version of Terminix as well as the version of dependent components.'
complete -c terminix -s w -l working-directory --description 'Set the working directory of the terminal.'
complete -c terminix -s p -l profile --description 'Set the starting profile using the name of one of the existing profiles.'
complete -c terminix -s t -l title --description 'Set the title of the new terminal.'
complete -c terminix -s s -l session --description 'Open the specified session file which has been previously saved.'
complete -c terminix -s a -l action --description 'Performs an action in the current Terminix instance, the following actions ar…'
complete -c terminix -s e -l command --description 'Executes all text after this parameter as a command, thus this parameter must…'
complete -c terminix -l maximize --description 'Maximize the terminal window.'
complete -c terminix -l minimize --description 'Minimize the terminal window.'
complete -c terminix -l full-screen --description 'Full-screen the terminal window.'
complete -c terminix -l focus-window --description 'Focus the existing window.'
complete -c terminix -l new-process --description 'Start an additional Terminix instance as a new process.'
complete -c terminix -l geometry --description 'Set the window size; for example: 80x24, or 80x24+200+200 (COLSxROWS+X+Y).'
complete -c terminix -s q -l quake --description 'Opens a window in quake mode or toggles existing quake mode window visibility.'
complete -c terminix -l preferences --description 'Show the Terminix preferences dialog directly.  SEE ALSO None.'

