# tiffgamut
# Autogenerated from man page /usr/share/man/man1/tiffgamut.1.gz
complete -c tiffgamut -s v --description 'Verbose.'
complete -c tiffgamut -s d --description 'Surface resolution details 1. 0 - 50. 0.'
complete -c tiffgamut -s w --description 'emit VRML . wrl file as well as CGATS . gam file.'
complete -c tiffgamut -s n --description 'Don\'t add VRML axes or white/black point.'
complete -c tiffgamut -s k --description 'Add markers for prim.  & sec.  "cusp" points.'
complete -c tiffgamut -s f --description 'Filter by popularity, perc = percent to use.'
complete -c tiffgamut -s i --description 'p = perceptual, r = relative colorimetric, s = saturation, a = absolute (defa…'
complete -c tiffgamut -s p --description 'l = Lab_PCS (default), j = CIECAM02 Appearance Jab.'
complete -c tiffgamut -s o --description 'n = normal (priority: lut > matrix > monochrome) r = reverse (priority: monoc…'
complete -c tiffgamut -s c --description 'set appearance mode and viewing conditions for CIECAM02, either an enumerated…'
complete -c tiffgamut -s O --description '.'

