# timage
# Autogenerated from man page /usr/share/man/man1/timage.1.gz
complete -c timage -s t --description 'Generate rectangular gamut boundary test chart.'
complete -c timage -s p --description 'Generate a colorspace step chart with L* steps^2.'
complete -c timage -s r --description 'Resolution in DPI (default 200).'
complete -c timage -s s --description 'Smooth blend.'
complete -c timage -s x --description '16 bit output.'
complete -c timage -s 4 --description 'CMYK output.'
complete -c timage -s g --description 'Percentage towards grey (default 0%).'

