# tplist-bpfcc
# Autogenerated from man page /usr/share/man/man8/tplist-bpfcc.8.gz
complete -c tplist-bpfcc -s p --description 'Display the USDT probes from all the libraries loaded by the specified proces…'
complete -c tplist-bpfcc -s l --description 'Display the USDT probes from the specified library or executable.'
complete -c tplist-bpfcc -s v --description 'Display the variables associated with the tracepoint or USDT probe.'

