# trace-bpfcc
# Autogenerated from man page /usr/share/man/man8/trace-bpfcc.8.gz
complete -c trace-bpfcc -s h --description 'Print usage message.'
complete -c trace-bpfcc -s p --description 'Trace only functions in the process PID.'
complete -c trace-bpfcc -s v --description 'Display the generated BPF program, for debugging purposes.'
complete -c trace-bpfcc -s z --description 'When collecting string arguments (of type char*), collect up to STRING_SIZE  …'
complete -c trace-bpfcc -s S --description 'If set, trace messages from trace\'s own process.'
complete -c trace-bpfcc -s M --description 'Print up to MAX_EVENTS trace messages and then exit.'
complete -c trace-bpfcc -s o --description 'Print times relative to the beginning of the trace (offsets), in seconds.'

