# txt2ti3
# Autogenerated from man page /usr/share/man/man1/txt2ti3.1.gz
complete -c txt2ti3 -s 2 --description 'Create dummy . ti2 file as well.'
complete -c txt2ti3 -s l --description 'set ink limit, 0 - 400% (default max in file).'
complete -c txt2ti3 -s d --description 'Set type of device as Display, not Output.'
complete -c txt2ti3 -s i --description 'Set type of device as Input, not Output.'

