# usbip
# Autogenerated from man page /usr/share/man/man1/usbip.8.gz
complete -c usbip -l debug --description 'Print debugging information.'
complete -c usbip -l log --description 'Log to syslog.'
complete -c usbip -l tcp-port --description 'Connect to PORT on remote host (used for attach and list --remote).  COMMANDS.'

