# usbipd
# Autogenerated from man page /usr/share/man/man1/usbipd.8.gz
complete -c usbipd -s 4 -l ipv4 --description 'Bind to IPv4.  Default is both.'
complete -c usbipd -s 6 -l ipv6 --description 'Bind to IPv6.  Default is both.'
complete -c usbipd -s D -l daemon --description 'Run as a daemon process.'
complete -c usbipd -s d -l debug --description 'Print debugging information.'
complete -c usbipd -o PFILE -l pid --description 'Write process id to FILE.'
complete -c usbipd -o tPORT -l tcp-port --description 'Listen on TCP/IP port PORT.'
complete -c usbipd -s h -l help --description 'Print the program help message and exit.'
complete -c usbipd -s v -l version --description 'Show version.  LIMITATIONS.'

