# uuid
# Autogenerated from man page /usr/share/man/man1/uuid.1.gz
complete -c uuid -s v --description 'Sets the version of the generated \\s-1DCE 1. 1\\s0 variant \\s-1UUID.'
complete -c uuid -s m --description 'Forces the use of a random multi-cast \\s-1MAC\\s0 address when generating vers…'
complete -c uuid -s n --description 'Generate count UUIDs instead of just a single one (the default).'
complete -c uuid -s 1 --description 'If option -n is used with a count greater than \\f(CW1, then this option can e…'
complete -c uuid -s F --description 'Representation format for importing or exporting an \\s-1UUID.'
complete -c uuid -s o --description 'Write output to filename instead of to stdout.'

