# viewgam
# Autogenerated from man page /usr/share/man/man1/viewgam.1.gz
complete -c viewgam -s c --description 'Color to make gamut, r = red, g = green, b = blue c = cyan, m = magenta, y = …'
complete -c viewgam -s t --description 'Set transparency from 0. 0 (opaque) to 1. 0 (invisible).'
complete -c viewgam -s w --description 'Show as a wireframe.'
complete -c viewgam -s s --description 'Show as a solid surace.'
complete -c viewgam -s n --description 'Don\'t add Lab axes.'
complete -c viewgam -s k --description 'Add markers for prim.  & sec.  "cusp" points.'
complete -c viewgam -s i --description 'Compute and print intersecting volume of first 2 gamuts.'
complete -c viewgam -s I --description 'Same as -i, but save intersection gamut to isect. gam.'

