# wakeuptime-bpfcc
# Autogenerated from man page /usr/share/man/man8/wakeuptime-bpfcc.8.gz
complete -c wakeuptime-bpfcc -s h --description 'Print usage message.'
complete -c wakeuptime-bpfcc -s f --description 'Print output in folded stack format.'
complete -c wakeuptime-bpfcc -s u --description 'Only trace user threads (not kernel threads).'
complete -c wakeuptime-bpfcc -s v --description 'Show raw addresses (for non-folded format).'
complete -c wakeuptime-bpfcc -s p --description 'Trace this process ID only (filtered in-kernel).'

