# x86_energy_perf_policy
# Autogenerated from man page /usr/share/man/man8/x86_energy_perf_policy.8.gz
complete -c x86_energy_perf_policy -s c --description 'The default is to operate on all CPUs.'
complete -c x86_energy_perf_policy -s v --description 'x86_energy_perf_policy is silent.'
complete -c x86_energy_perf_policy -s r --description 'is read and displayed.'

