# zfsdist-bpfcc
# Autogenerated from man page /usr/share/man/man8/zfsdist-bpfcc.8.gz
complete -c zfsdist-bpfcc -s h --description 'Print usage message.'
complete -c zfsdist-bpfcc -s T --description 'Don\'t include timestamps on interval output.'
complete -c zfsdist-bpfcc -s m --description 'Output in milliseconds.'
complete -c zfsdist-bpfcc -s p --description 'Trace this PID only.  EXAMPLES.'

