# zsync
# Autogenerated from man page /usr/share/man/man1/zsync.1.gz
complete -c zsync -s A --description 'Specifies a username and password to be used with the given hostname.'
complete -c zsync -s i --description 'Specifies (extra) input files.'
complete -c zsync -s k --description 'Indicates that zsync should save the zsync file that it downloads, with the g…'
complete -c zsync -s o --description 'Override the default output file name.'
complete -c zsync -s q --description 'Suppress the progress bar, download rate and ETA display.'
complete -c zsync -s s --description 'Deprecated synonym for -q.'
complete -c zsync -s u --description 'This specifies the referring URL.   If you have a .'

