# zsyncmake
# Autogenerated from man page /usr/share/man/man1/zsyncmake.1.gz
complete -c zsyncmake -s b --description 'Specify the blocksize to the underlying rsync algorithm.'
complete -c zsyncmake -s C --description 'Tells zsyncmake not to generate any instructions in the .'
complete -c zsyncmake -s e --description 'Tells zsyncmake that the client must be able to receive the exact file that w…'
complete -c zsyncmake -s f --description 'Set the filename to include in the output file (this is what the file will be…'
complete -c zsyncmake -s o --description 'Override the default output file name.'
complete -c zsyncmake -s u --description 'Specifies the URL from which users can download the content of the supplied f…'
complete -c zsyncmake -s U --description 'Specifies a URL corresponding to the decompressed content of the file (only a…'
complete -c zsyncmake -s v --description 'Enable verbose messages.'
complete -c zsyncmake -s V --description 'Prints the version of zsync.'
complete -c zsyncmake -s z --description 'Compress the file to transfer.'
complete -c zsyncmake -s Z --description 'zsyncmake automatically looks inside gzip compressed files and exports the un…'

