#!/bin/bash

#kubectl create secret generic -n $1 oauth2-cookie --from-literal=cookieSecret="$(head -n 5 /dev/urandom | base64 | cut -c 64 | tr -d '\n')"

cookie="$(head -n 5 /dev/urandom | base64 | cut -c 64 | tr -d '\n')"
cookie_enc="$(echo "$cookie" | base64)"
cat <<E | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-cookie
  namespace: "$1"
data:
  cookieSecret: "$cookie_enc"
E
