---
bases:
  - ../../common/environments.yaml
  - ../../common/repos.yaml
  - ../../common/helmdefaults.yaml

---
environments:
  default:
    values:
      - config.yaml
    secrets:
      - secrets.yaml

---
releases:
  - name: cert-manager
    namespace: {{ .Values.certmanager.namespace }}
    createNamespace: true
    labels:
      app: cert-manager
    chart: jetstack/cert-manager
    version: {{ .Values.certmanager.version }}
    values:
      - values.yaml.gotmpl
{{- if .Values.blsceksauxclusterissuer.enabled }}
  - name: stable-eks-auxillary-setup-ext-clusterissuer
    namespace: {{ .Values.blscauxclusterissuer.namespace }}
    createNamespace: true
    labels:
      tier: "secrets-management"
      app: cert-manager
    chart: stable/stable-eks-aux
    version: {{ .Values.blscauxclusterissuer.version }}
    values:
      - cluster-issuer-values.yaml
{{- end }}
