aws_partition: ENC[AES256_GCM,data:8Cx5wuapbpSo2dXh,iv:yl1h6HGkLQLJnZ+KW676CCsdYTebGKy3W7LOaSKSf9Q=,tag:F4EHZYb35qAxUa/epE0SXQ==,type:int]
aws_account_id: ENC[AES256_GCM,data:UOvBYeP4vkiMe1qBMdmBz8Z3Aw==,iv:94buhW1PeiisFZTom6i6bttlwEiv7KghiqlISV3fGJA=,tag:1/wIfqKoxG+R+gvvktfJ5Q==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-west-2:429863676324:key/4b2c5901-43aa-4e1c-b14d-bb797a476939
        created_at: '2021-04-14T20:23:05Z'
        enc: AQICAHg6SOC/ZGlqvvXyT21QxXdmVYeYJHrDafTRlAN/L3qiPQGJGS+ulyDol1xJCxowEq3wAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMR9LOAueGP2C3nNpSAgEQgDto/P5lrrqVv1ycT22MteREG65TAZbyk7WI1doRRsnOCt6PyZJASbD5erNrAzUpLyCnEtBtOAofFqbMYA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-14T20:38:25Z'
    mac: ENC[AES256_GCM,data:2mEprnv2uySiKHHsDJJ4L64ZHTWBVM0LWARKxPQix+AGUjq9ugLki4/ybyjmq5hcI52R2jG3teMJLwe9pMXJ8/iJdIwQm7y0b+CSGIf1jHJal3oEMcSAupXQk/1hEcDV1scrsvbYdBTYBTl+RuNHOmFvFSGh9uKzISRTv6Sti/Q=,iv:z0vTtGHrJAOtgddNpbmfeWFEcWQ3r4IIQV2cOeQEEFM=,tag:NybcqzCFuj8aqDUUAE3tBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
